"""empty message

Revision ID: ad69573a14e9
Revises: 6dcab6f1a281
Create Date: 2016-01-26 19:18:12.286438

"""

# revision identifiers, used by Alembic.
revision = 'ad69573a14e9'
down_revision = '6dcab6f1a281'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('blog',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('body', sa.String(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('blog')
    ### end Alembic commands ###
